; platformio.ini
[env:m5stick-s3]
platform = espressif32
board = m5stick-s3
framework = arduino
monitor_speed = 115200
build_flags = -D NIGHT_MODE_DISABLE=0
lib_deps =
    # Add libs if you prefer a more feature-rich display or time libs
    # For example:
    #  adafruit/Adafruit GFX Library@^1.10.14
